# Generated by Django 4.1.3 on 2023-01-11 00:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrederItem',
            new_name='OrderItem',
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['pk']},
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
