# Generated by Django 4.1.3 on 2023-01-13 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_orederitem_orderitem_alter_order_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quality',
            new_name='quantity',
        ),
    ]
